### ISSUE TITLE
Review Nexus work directory

### ISSUE THREAD

**Issue by ttres** [instruct-br/puppet-nexus#12]
By default, the Nexus binary install file contains a directory, `sonatype-work`, where all files kept by the repository are created. So far, so good.

But, cause this work directory is glued together with the installation directory, probably it will exist outside `/var` filesystem, which is its right place (IMHO, following [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)).

I think this situation will worse the update procedure, too, in many ways.

Considerations?

**Comment by Igorolivei** [comment]
Indeed the `/var` directory is a better place to put the `sonatype-work` directory. 

To update the Nexus, only the application directory should be modified (you can read more [here](https://support.sonatype.com/hc/en-us/articles/115000350007?_ga=2.244749381.1576315964.1524944115-665555677.1524447724)). So, putting the work directory in `/var` will also ease the development of the update procedure in this module, since the work directory will not be overwritten when the binary file is extracted.

This commit makes changes to move the work directory to `/var/lib/nexus` after the binary file extraction. It also adds a parameter `data_path` and modifies the data on hiera to include a default value for this new parameter. However, after moving the work dir, there's still a `sonatype-work` at `/opt/nexus` that is not used, and I still don't know why.
